services:
  mysql:
    image: mysql:8.4.2
    container_name: __YOUR_PROJECT_NAME___mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: __YOUR_PROJECT_NAME__
    ports:
      - '3306:3306'
    volumes:
      - __YOUR_PROJECT_NAME___mysql_data:/var/lib/mysql

volumes:
  ai_questioning_mysql_data:
