services:
  mysql:
    image: mysql:8.4.2
    container_name: events_mcp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-234567}
      MYSQL_DATABASE: ${DB_NAME:-events_mcp}
    ports:
      - '${DB_PORT:-3308}:3306'
    volumes:
      - events_mcp_mysql_data:/var/lib/mysql

volumes:
  events_mcp_mysql_data:
