services:
  mysql:
    image: mysql:8.4.2
    container_name: yourprojectname_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: yourprojectname
    ports:
      - '3306:3306'
    volumes:
      - yourprojectname_mysql_data:/var/lib/mysql

volumes:
  yourprojectname_mysql_data:
